/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 2;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int BUILT_IN_CODE = 11;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;
  /** Lexical state. */
  int IN_BUILT_IN_CODE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<INTEGER>",
    "\"\\\"\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"\\\"\"",
    "\"`\"",
    "<token of kind 9>",
    "\"\\\\`\"",
    "\"`\"",
  };

}
